services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly_cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      timeout: 3s
    environment:
      - DRAGONFLY_MEMORY_LIMIT=4gb
      - DRAGONFLY_PROACTIVE_THREADS=4
    deploy:
      resources:
        limits:
          cpus: '4'

  postgres:
    image: postgres:13
    container_name: spring_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d todo" ]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      dragonfly:
        condition: service_healthy

