spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://postgres:5432/todo
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 2592000 # 1 month

base-url: http://localhost:8080